stages:
    - deploy

pages:
  image: registry.gitlab.com/avatar-cli/website/zola:latest
  stage: deploy
  script:
    - git submodule init
    - git submodule update
    - zola build
  artifacts:
    paths:
      - public
  only:
    - main
